spring.application.name=thymeleafdemo

countries=Brazil,Canada,France,Germany,India,Mexico,Spain,United States

programmingLanguages=C,Go,Java,Kotlin,Python

operatingSystems=Linux,macOS,Microsoft Windows